- name: Set SELinux context for Prometheus config
  community.general.sefcontext:
    target: "{{ prom_srv_dir }}/etc(/.*)?"
    setype: container_file_t
    state: present

- name: Apply SELinux context
  ansible.builtin.command:
    cmd: "restorecon -R {{ prom_srv_dir }}/etc"
  changed_when: false
